--1) Create a function to calculate simple interest (SI=P*R*N/100). (A) 
CREATE OR ALTER FUNCTION FN_SIMPLE_INTEREST
(
	@P INT,
	@R DECIMAL(10,2),
	@T INT
)
RETURNS DECIMAL(10,2)
AS
BEGIN
DECLARE @SI DECIMAL(10,2)
SET @SI=(@P*@R*@T)/100
RETURN @SI
END

SELECT dbo.FN_SIMPLE_INTEREST(1000,10.2,10) AS SIMPLE_INTEREST;
--2) Create a function to find the feet to inch. (A) 
CREATE OR ALTER FUNCTION FN_FEET
(
	@INCH DECIMAL(10,2)
)
RETURNS DECIMAL(10,2)
AS
BEGIN
DECLARE @FEET DECIMAL(10,2)
SET @FEET = (@INCH)/12
RETURN @FEET
END

SELECT DBO.FN_FEET(12) AS FEET
--3) Create a function to convert Celsius to Fahrenheit. (B) 
CREATE OR ALTER FUNCTION CELCIUS_FAHRENHEIT
(
	@CELCIUS DECIMAL(10,2)
)
RETURNS DECIMAL(10,2)
AS
BEGIN
DECLARE @FAHRENHEIT DECIMAL(10,2)
SET @FAHRENHEIT = (@CELCIUS * 9.0 / 5.0) + 32
RETURN @FAHRENHEIT
END

SELECT DBO.CELCIUS_FAHRENHEIT(10) AS FAHRENHEIT
--4) Create a function to find factorial of a number. (C) 
CREATE OR ALTER FUNCTION FN_FACT
(
	@N INT
)
RETURNS INT
AS
BEGIN
DECLARE @FACT INT
DECLARE @I INT
SET @FACT=1
SET @I = 1
WHILE @N>=1
BEGIN
SET @FACT = @FACT*@I
SET @I = @I+1
SET @N = @N-1
END
RETURN @FACT
END

SELECT DBO.FN_FACT(4) AS FACTORIAL
--5) Write a function to find the sum of odd numbers between two range. (C) 
CREATE OR ALTER FUNCTION FN_ODD_SUM_RANGE
(
    @N1 INT,
    @N2 INT
)
RETURNS INT
AS
BEGIN
    DECLARE @TOTAL INT

    SET @TOTAL = 0

    WHILE @N1 <= @N2
    BEGIN
        IF @N1 % 2 <> 0
            SET @TOTAL = @TOTAL + @N1

        SET @N1 = @N1 + 1
    END

    RETURN @TOTAL
END

SELECT DBO.FN_ODD_SUM_RANGE(11,20) AS TOTAL