--1) Write T - SQL block to perform Dynamic cursor. (A) 
DECLARE @BANK_ID INT
DECLARE @BANK_NAME VARCHAR(50)

DECLARE CUR_BANK CURSOR DYNAMIC
FOR
SELECT BANK_ID, BANK_NAME
FROM BANK_MASTER

OPEN CUR_BANK

FETCH NEXT FROM CUR_BANK
INTO @BANK_ID, @BANK_NAME

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT CAST(@BANK_ID AS VARCHAR(10))
	      + ' ' + @BANK_NAME

	FETCH NEXT FROM CUR_BANK
	INTO @BANK_ID, @BANK_NAME
END

CLOSE CUR_BANK
DEALLOCATE CUR_BANK
--2) Write T- SQL block to perform Dynamic cursor that fetch value and print that value after some delay. (B)
DECLARE @BANK_ID INT

DECLARE CUR_BANK CURSOR DYNAMIC
FOR
SELECT BANK_ID
FROM BANK_MASTER

OPEN CUR_BANK

FETCH NEXT FROM CUR_BANK
INTO @BANK_ID

WHILE @@FETCH_STATUS = 0
BEGIN
	WAITFOR DELAY '00:00:02'

	PRINT @BANK_ID

	FETCH NEXT FROM CUR_BANK
	INTO @BANK_ID
END

CLOSE CUR_BANK
DEALLOCATE CUR_BANK