--1) Create a DML After/For Trigger for INSERT event and display the message of the successful event. (A) 
CREATE OR ALTER TRIGGER TR_INSERT
ON BANK_MASTER
AFTER INSERT
AS
BEGIN
	PRINT 'INSERT SUCCESSFUL'
END

INSERT INTO BANK_MASTER
VALUES (11,'YES BANK','YES')
--2) Create a DML After/For Trigger for the UPDATE event and display a message of the successful event. (A) 
CREATE OR ALTER TRIGGER TR_UPDATE
ON BANK_MASTER
AFTER UPDATE
AS
BEGIN
	PRINT 'UPDATE SUCCESSFUL'
END

UPDATE BANK_MASTER
SET BANK_NAME='YES BANK LTD'
WHERE BANK_ID=11
--3) Create a DML After/For Trigger for the DELETE event and display the message of the successful event. (A) 
CREATE OR ALTER TRIGGER TR_DELETE
ON BANK_MASTER
AFTER DELETE
AS
BEGIN
	PRINT 'DELETE SUCCESSFUL'
END

DELETE FROM BANK_MASTER
WHERE BANK_ID=11
--4) Create a DML After/For Trigger for All three-event using log table. (B) 
CREATE TABLE DML_LOG
(
	LOG_MSG VARCHAR(50)
)

CREATE OR ALTER TRIGGER TR_DML_LOG
ON BANK_MASTER
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	IF EXISTS (SELECT * FROM inserted)
	   AND EXISTS (SELECT * FROM deleted)
		INSERT INTO DML_LOG
		VALUES ('UPDATE')

	ELSE IF EXISTS (SELECT * FROM inserted)
		INSERT INTO DML_LOG
		VALUES ('INSERT')

	ELSE IF EXISTS (SELECT * FROM deleted)
		INSERT INTO DML_LOG
		VALUES ('DELETE')
END

SELECT * FROM DML_LOG