--1) Display Employee number, name and branch name. (A) 
SELECT EMP_NO,EMP_FULLNAME,BRANCH_NAME 
FROM EMPLOYEE_MASTER JOIN BRANCH_MASTER
ON EMPLOYEE_MASTER.BRANCH_IFSC=BRANCH_MASTER.BRANCH_IFSC

--2) Display Account number, customer id, name and branch IFSC code using join. (A) 
SELECT ACC_NO,CUSTOMER_MASTER.CUST_ID,CUST_FULLNAME,BRANCH_IFSC
FROM ACCOUNT_MASTER JOIN CUSTOMER_MASTER
ON ACCOUNT_MASTER.CUST_ID = CUSTOMER_MASTER.CUST_ID

--3) Display Transaction ID, amount, account number, account type whose transaction type is Online. (A) 
SELECT TRAN_ID, TRAN_AMOUNT,TRAN_ACC_NO, ACC_TYPE
FROM TRANSACTION_MASTER
JOIN ACCOUNT_MASTER
ON TRANSACTION_MASTER.TRAN_ACC_NO = ACCOUNT_MASTER.ACC_NO
WHERE TRAN_TYPE = 'OL';

--4) Display Account number, type, transaction account number and amount using left outer join. (A) 
SELECT ACC_NO, ACC_TYPE,TRAN_ACC_NO, TRAN_AMOUNT
FROM ACCOUNT_MASTER
LEFT OUTER JOIN TRANSACTION_MASTER
ON ACCOUNT_MASTER.ACC_NO = TRANSACTION_MASTER.TRAN_ACC_NO;
--5) Display Account number, type, transaction account number and amount using right outer join. (A) 
SELECT ACC_NO, ACC_TYPE,TRAN_ACC_NO, TRAN_AMOUNT
FROM ACCOUNT_MASTER
RIGHT OUTER JOIN TRANSACTION_MASTER
ON ACCOUNT_MASTER.ACC_NO = TRANSACTION_MASTER.TRAN_ACC_NO;
--6) Display customer name, mobile number who has highest transaction amount. (A) 
SELECT TOP 1 CUST_FULLNAME, CUST_MOBILENO
FROM CUSTOMER_MASTER JOIN ACCOUNT_MASTER
ON CUSTOMER_MASTER.CUST_ID = ACCOUNT_MASTER.CUST_ID
JOIN TRANSACTION_MASTER
ON ACCOUNT_MASTER.ACC_NO = TRANSACTION_MASTER.TRAN_ACC_NO
ORDER BY TRAN_AMOUNT DESC
--7) Display Branch name, IFSC and Bank ID who has lowest paying amount employee. (A) 
SELECT TOP 1 BRANCH_NAME,
       BRANCH_MASTER.BRANCH_IFSC,
       BANK_ID
FROM BRANCH_MASTER
JOIN EMPLOYEE_MASTER
ON BRANCH_MASTER.BRANCH_IFSC = EMPLOYEE_MASTER.BRANCH_IFSC
ORDER BY EMPLOYEE_SALARY ASC;
--8) Display the count of total designation of an employees. (A) 
SELECT EMP_DESIGNATION,
       COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE_MASTER
GROUP BY EMP_DESIGNATION;
--9) Display the count of how many customers have saving account. (A) 
SELECT COUNT(*) AS TOTAL_SAVING_CUSTOMERS
FROM ACCOUNT_MASTER
WHERE ACC_TYPE = 'SB';
--10) Display details of branch master branch name wise in descending order. (A) 
SELECT *
FROM BRANCH_MASTER
ORDER BY BRANCH_NAME DESC;