--1) Create a DDL Trigger for CREATE event and display message of successful event. (A) 
CREATE OR ALTER TRIGGER TR_CREATE
ON DATABASE
FOR CREATE_TABLE
AS
BEGIN
    PRINT 'CREATE EVENT SUCCESSFULLY EXECUTED'
END
--2) Create a DDL Trigger for ALTER event and display message of successful event. (A) 
CREATE OR ALTER TRIGGER TR_ALTER
ON DATABASE
FOR ALTER_TABLE
AS
BEGIN
    PRINT 'ALTER EVENT SUCCESSFULLY EXECUTED'
END
--3) Create a DDL Trigger for DROP event and display message of successful event. (A) 
CREATE OR ALTER TRIGGER TR_DROP
ON DATABASE
FOR DROP_TABLE
AS
BEGIN
    PRINT 'DROP EVENT SUCCESSFULLY EXECUTED'
END
--4) Create a DDL Trigger for All three events using log table. (B) 
CREATE TABLE DDL_LOG
(
	LOG_MSG VARCHAR(100)
)

CREATE OR ALTER TRIGGER TR_DDL_LOG
ON DATABASE
FOR CREATE_TABLE, ALTER_TABLE, DROP_TABLE
AS
BEGIN
	INSERT INTO DDL_LOG
	VALUES ('DDL EVENT OCCURRED')
END

SELECT * FROM DDL_LOG