--1) Write T - SQL block to perform Static cursor. (A) 
DECLARE @BANK_ID INT
DECLARE @BANK_NAME VARCHAR(50)

DECLARE CUR_BANK CURSOR STATIC
FOR
SELECT BANK_ID, BANK_NAME
FROM BANK_MASTER

OPEN CUR_BANK

FETCH NEXT FROM CUR_BANK
INTO @BANK_ID, @BANK_NAME

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT CAST(@BANK_ID AS VARCHAR(10))
	      + ' ' + @BANK_NAME

	FETCH NEXT FROM CUR_BANK
	INTO @BANK_ID, @BANK_NAME
END

CLOSE CUR_BANK
DEALLOCATE CUR_BANK
--2) Write T – SQL block to perform static cursor that fetches first and last value from the result set. (B) 
DECLARE @BANK_ID INT
DECLARE @BANK_NAME VARCHAR(50)

DECLARE CUR_BANK CURSOR STATIC
FOR
SELECT BANK_ID, BANK_NAME
FROM BANK_MASTER

OPEN CUR_BANK

-- First Record
FETCH FIRST FROM CUR_BANK
INTO @BANK_ID, @BANK_NAME

PRINT 'FIRST RECORD'
PRINT CAST(@BANK_ID AS VARCHAR(10))
      + ' ' + @BANK_NAME

-- Last Record
FETCH LAST FROM CUR_BANK
INTO @BANK_ID, @BANK_NAME

PRINT 'LAST RECORD'
PRINT CAST(@BANK_ID AS VARCHAR(10))
      + ' ' + @BANK_NAME

CLOSE CUR_BANK
DEALLOCATE CUR_BANK
--3) Write T -SQL block to perform static cursor and try to insert/update/delete a record on table. (C) 
DECLARE @BANK_ID INT
DECLARE @BANK_NAME VARCHAR(50)

DECLARE CUR_BANK CURSOR STATIC
FOR
SELECT BANK_ID, BANK_NAME
FROM BANK_MASTER

OPEN CUR_BANK

FETCH NEXT FROM CUR_BANK
INTO @BANK_ID, @BANK_NAME

-- Insert
INSERT INTO BANK_MASTER
VALUES (11,'YES BANK','YES')

-- Update
UPDATE BANK_MASTER
SET BANK_NAME='SBI LTD'
WHERE BANK_ID=1

-- Delete
DELETE FROM BANK_MASTER
WHERE BANK_ID=10

FETCH NEXT FROM CUR_BANK
INTO @BANK_ID, @BANK_NAME

CLOSE CUR_BANK
DEALLOCATE CUR_BANK